livro/EmprestimoLivros/Models/EmprestimoModel.cs
using System.ComponentModel.DataAnnotations;

namespace EmprestimoLivros.Models
{
    public class EmprestimoModel
    {

        
        public int Id { get; set; }

        [Required(ErrorMessage = "Digite o nome do receptor!")]
        public string Receptor{ get; set; }

        [Required(ErrorMessage = "Digite o nome do fornecedor!")]
        public string Fornecedor { get; set;}

        [Required(ErrorMessage = "Digite o nome do livro!")]
        public string LivroEmprestado { get; set;}

        public DateTime DataUltimaAtualizacao { get; set;} = DateTime.Now; 
    }
}

livro/EmprestimoLivros/Models/ErrorViewModel.cs
namespace EmprestimoLivros.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

livro/EmprestimoLivros/Controllers/EmprestimoController.cs
using EmprestimoLivros.Data;
using EmprestimoLivros.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Cryptography.Xml;

namespace EmprestimoLivros.Controllers
{
    public class EmprestimoController : Controller
    {
        private readonly ApplicationDbContext _db;

        public EmprestimoController(ApplicationDbContext db)
        {
                _db = db;
        }
        public IActionResult Index()
        {
            IEnumerable<EmprestimoModel> emprestimos = _db.EmprestimoModels;
            
            return View(emprestimos);
        }
        [HttpGet]
        public IActionResult Registar()
        {
            return View();
        }

        [HttpGet]

        public IActionResult Editar(int? Id) 
        {
            if(Id ==null || Id == 0)
            {
                return NotFound();
            }
            EmprestimoModel emprestimo = _db.EmprestimoModels.FirstOrDefault(x => x.Id == Id);
            
            if(emprestimo == null)
            {
                return NotFound();
            }
           
            return View(emprestimo);
        }

        [HttpGet]

        public IActionResult Excluir(int? Id) 
        {
            if (Id == null || Id == 0)
            {
                return NotFound();
            }

            EmprestimoModel emprestimo = _db.EmprestimoModels.FirstOrDefault(x =>x.Id == Id);   

            if(emprestimo == null) 
            {
                return NotFound();
            }
            return View(emprestimo);
        }
        
        
         
        [HttpPost]
        public IActionResult Registar(EmprestimoModel emprestimos) 
        {
            if (ModelState.IsValid)
            {
                _db.EmprestimoModels.Add(emprestimos);
                _db.SaveChanges();

                TempData["MensagemSucesso"] = "Registo efetuado com sucesso!";
                
                return RedirectToAction("Index");
            }
            TempData["MensagemErro"] = "Erro ao tentar adicionar registo, tente novamente";
            return View();
        }

        [HttpPost]
        
        public IActionResult Editar(EmprestimoModel emprestimo)
        {
            if (ModelState.IsValid)
            {
                _db.EmprestimoModels.Update(emprestimo);
                _db.SaveChanges();

                TempData["MensagemSucesso"] = "Edição efetuada com sucesso!";
                
                return RedirectToAction("Index");

                
            }

            TempData["MensagemErro"] = "Erro ao tentar editar, tente novamente";
            return View(); 
        }

        [HttpPost]

        public IActionResult Excluir(EmprestimoModel emprestimo) 
        {
            if (emprestimo == null)
            {
                return NotFound();

            }

            _db.EmprestimoModels.Remove(emprestimo);
            _db.SaveChanges();

            TempData["MensagemSucesso"] = "Exclusão efetuada com sucesso!";
            return RedirectToAction("Index");

           
        }

        



    }
}

livro/EmprestimoLivros/Controllers/HomeController.cs
using EmprestimoLivros.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace EmprestimoLivros.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

livro/EmprestimoLivros/Views/Emprestimo/Editar.cshtml
@model EmprestimoModel


@{

    ViewData["tittle"] = "Editar empréstimo";
}
<div class="container bg-dark p-5 rounded-5">

    <div class="mb-5 text-center">
        <h1 class="text-light">Edição de Empréstimos</h1>
    </div>


    <form method="post" asp-controller="Emprestimo" asp-action="Editar">

        <input  type="hidden" asp-for="Id"/>
        <div class="mb-3">
            <label for="Receptor" class="form-label text-light">Receptor</label>
            <input type="text" class="form-control text-light" asp-for="Receptor" id="Receptor" placeholder="Quem está a receber o livro?">
            <span asp-validation-for="Receptor " class="text-danger"></span>

        </div>


        <div class="mb-3">
            <label for="Fornecedor" class="form-label text-light ">Fornecedor</label>
            <input type="text" class="form-control text-light" asp-for="Fornecedor" id="Fornecedor" placeholder="Quem está a emprestar o livro?">
            <span asp-validation-for="Fornecedor" class="text-danger"></span>
        </div>


        <div class="mb-3">
            <label for="Livro" class="form-label text-light">Livro</label>
            <input type="text" class="form-control text-light" asp-for="LivroEmprestado" id="Livro" placeholder="Qual é o nome do livro?">
            <span asp-validation-for="LivroEmprestado" class="text-danger"></span>
        </div>


        <div class="d-flex gap-5 mt-5">
            <button type="submit" class="btn btn-success w-50">Editar</button>
            <a class="btn btn-primary w-50" asp-controller="Emprestimo" asp-action="Index">Voltar</a>
        </div>
    </form>
</div>

livro/EmprestimoLivros/Views/Emprestimo/Excluir.cshtml
@model EmprestimoModel


@{

    ViewData["tittle"] = "Excluir empréstimo";
}
<div class="container bg-dark p-5 rounded-5">

    <div class="mb-5 text-center">
        <h1 class="text-light">Excluir</h1>
        
    </div>


    <form method="post" asp-controller="Emprestimo" asp-action="Excluir">

        <input type="hidden" asp-for="Id" />
        <h2 class="text-light mb-5 text-center">Tem a certeza que deseja excluir o registo?</h2>
        <div class="mb-3">
            <label for="Receptor" class="form-label text-light">Receptor</label>
            <input type="text" class="form-control text-light" asp-for="Receptor" id="Receptor" placeholder="Quem está a receber o livro?" disabled>
            <span asp-validation-for="Receptor " class="text-danger"></span>

        </div>


        <div class="mb-3">
            <label for="Fornecedor" class="form-label text-light ">Fornecedor</label>
            <input type="text" class="form-control text-light" asp-for="Fornecedor" id="Fornecedor" placeholder="Quem está a emprestar o livro?" disabled>
            <span asp-validation-for="Fornecedor" class="text-danger"></span>
        </div>


        <div class="mb-3">
            <label for="Livro" class="form-label text-light">Livro</label>
            <input type="text" class="form-control text-light" asp-for="LivroEmprestado" id="Livro" placeholder="Qual é o nome do livro?" disabled>
            <span asp-validation-for="LivroEmprestado" class="text-danger"></span>
        </div>


        <div class="d-flex gap-5 mt-5">
            <button type="submit" class="btn btn-danger w-50">Excluir</button>
            <a class="btn btn-primary w-50" asp-controller="Emprestimo" asp-action="Index">Voltar</a>
        </div>
    </form>
</div>

livro/EmprestimoLivros/Views/Emprestimo/Index.cshtml
@model IEnumerable<EmprestimoModel>

    <div class = "container" >


        <div class="d-flex justify-content-between align-items-center mb-5">
            <h1>Empréstimos</h1>
        <a class="btn btn-success mx-2" asp-controller="Emprestimo" asp-action="Registar" > <i class="bi bi-file-earmark-plus mx-2"></i>Adicionar </a>

        </div>

    @if(TempData["MensagemSucesso"] != null)
    {
        <div class="alert alert-sucess text-dark" role="alert">
            @TempData["MensagemSucesso"]
            </div>
    }

    @if (TempData["MensagemErro"] != null)
    {
        <div class="alert alert-danger text-light" role="alert">
            @TempData["MensagemErro"]
        </div>
    }
	
	<table id ="Emprestimos"class="table table-lighu table-hover mt-5">
    <thead>
        <tr>
            <th scope="col">Receptor</th>
            <th scope="col">Fornecedor</th>
            <th scope="col">Livro</th>
            <th scope="col">Ultima atualização</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @if(Model != null)
        {

            @foreach(var emprestimo in Model)
            {
                <tr>
                    <th scope="row">@emprestimo.Receptor</th>
                    <td>@emprestimo.Fornecedor</td>
                    <td>@emprestimo.LivroEmprestado</td>
                    <td>@emprestimo.DataUltimaAtualizacao</td>
                    <td>
                            <a asp-controller="Emprestimo" asp-action="Editar" asp-route-id="@emprestimo.Id" class="btn btn-warning mx-2">
                                <i class="bi bi-pencil-square"></i> Editar
                            </a>
                            <a asp-controller="Emprestimo" asp-action="Excluir" asp-route-id="@emprestimo.Id" class="btn btn-danger mx-2">
                                <i class="bi bi-trash3"></i> Excluir
                            </a>

                            
                    </td>
                </tr>
            }
            
        }

          
        
      
    </tbody>
</table>

    <a asp-controller="Home" class="btn btn-warning mx-2">
        <i class="bi bi-arrow-return-left"></i> Voltar
    </a>
</div>

livro/EmprestimoLivros/Views/Emprestimo/Registar.cshtml
@model EmprestimoModel
    

@{

    ViewData["tittle"] = "Registar Empréstimo";
}
<div class="container bg-dark p-5 rounded-5">

    <div class="mb-5 text-center">
        <h1 class="text-light">Registo de Empréstimos</h1>
    </div>


<form method="post" asp-controller="Emprestimo" asp-action="Registar">
    <div class="mb-3">
        <label for="Receptor" class="form-label text-light">Receptor</label>
        <input type="text" class="form-control text-light" asp-for="Receptor" id="Receptor" placeholder="Quem está a receber o livro?">
        <span asp-validation-for="Receptor " class="text-danger"></span>
        
    </div>
   
    
    <div class="mb-3">
        <label for="Fornecedor" class="form-label text-light ">Fornecedor</label>
        <input type="text" class="form-control text-light" asp-for="Fornecedor" id="Fornecedor" placeholder="Quem está a emprestar o livro?">
            <span asp-validation-for="Fornecedor" class="text-danger"></span>
    </div>

        
    <div class="mb-3">
         <label for="Livro" class="form-label text-light">Livro</label>
         <input type="text" class="form-control text-light"  asp-for="LivroEmprestado" id="Livro" placeholder="Qual é o nome do livro?">
            <span asp-validation-for="LivroEmprestado" class="text-danger"></span>
        </div>


        <div class="d-flex gap-5 mt-5">
            <button type="submit" class="btn btn-success w-50">Adicionar</button>
            <a class="btn btn-primary w-50" asp-controller="Emprestimo" asp-action="Index">Voltar</a>
        </div>
</form>   
</div>

livro/EmprestimoLivros/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Empréstimos online</h1>
    <p>"Leia mais, gaste menos, descubra um mundo de histórias com nossos livros emprestados!"</p>
<div>
<img src="/img/book4.png"/>
    </div>
</div>

livro/EmprestimoLivros/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Book Share</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/Materia.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EmprestimoLivros.styles.css" asp-append-version="true" />
    <link href="https://cdn.datatables.net/v/dt/dt-1.13.6/datatables.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">


</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-light" asp-area="" asp-controller="Home" asp-action="Index">Book Share</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index"><i class="bi bi-house-door mx-2"></i>Home</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Emprestimo" asp-action="Index"><i class="bi bi-book mx-2"></i>Empréstimos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
       
            @RenderBody()
            <main role="main" class="pb-3">
                <!-- Seu conteúdo principal existente aqui -->

                <section class="gallery">
                    <!-- Sua galeria de livros aqui -->
                </section>
            </main>

    
    
    
    
    
    </div>

    <footer class="border-top footer text-muted bg-dark" style="position: sticky; bottom: 0;">
        <div class="container text-light">
            <!-- Conteúdo do rodapé -->
            &copy; 2023 - Claudia Veloso || Mila Fernandes - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.datatables.net/v/dt/dt-1.13.6/datatables.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>